package Items;

import org.junit.Test;

import static org.assertj.core.api.Assertions.assertThat;


public class WordsTest {

    private static final String TEXT = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Euismod quis viverra nibh cras pulvinar mattis nunc sed. Quam adipiscing vitae proin sagittis nisl rhoncus mattis. Feugiat sed lectus vestibulum mattis ullamcorper velit. Nulla porttitor massa id neque aliquam. Mauris sit amet massa vitae. Tempus egestas sed sed risus pretium. Nec tincidunt praesent semper feugiat nibh. Dignissim cras tincidunt lobortis feugiat vivamus at augue eget arcu. Vitae nunc sed velit dignissim sodales ut eu. Condimentum id venenatis a condimentum.\n" +
            "\n" +
            "Orci a scelerisque purus semper. Quam adipiscing vitae proin sagittis. Nisl vel pretium lectus quam id leo in vitae. Tristique sollicitudin nibh sit amet commodo nulla facilisi. Diam ut venenatis tellus in metus vulputate eu scelerisque. Felis donec et odio pellentesque diam volutpat commodo sed. Enim sit amet venenatis urna cursus eget. Pretium nibh ipsum consequat nisl vel pretium. Nunc sed augue lacus viverra vitae. Bibendum enim facilisis gravida neque convallis a cras. Quis commodo odio aenean sed. Donec et odio pellentesque diam.\n" +
            "\n" +
            "Condimentum mattis pellentesque id nibh tortor id aliquet lectus. Feugiat in fermentum posuere urna nec tincidunt praesent semper feugiat. Orci dapibus ultrices in iaculis nunc. Sagittis orci a scelerisque purus semper eget duis at. Ac placerat vestibulum lectus mauris ultrices eros in cursus turpis. Consequat mauris nunc congue nisi. Aenean euismod elementum nisi quis. Dictumst quisque sagittis purus sit amet volutpat. Viverra suspendisse potenti nullam ac. Urna nec tincidunt praesent semper feugiat. Nunc congue nisi vitae suscipit tellus mauris. A condimentum vitae sapien pellentesque habitant morbi tristique senectus. Aliquam nulla facilisi cras fermentum odio eu feugiat. Sit amet luctus venenatis lectus magna fringilla urna. Et ultrices neque ornare aenean euismod elementum nisi quis.\n" +
            "\n" +
            "Eget mi proin sed libero enim. Lorem donec massa sapien faucibus et. Eget est lorem ipsum dolor sit. Penatibus et magnis dis parturient montes nascetur ridiculus mus. Condimentum vitae sapien pellentesque habitant morbi tristique. Sit amet nulla facilisi morbi tempus. Metus dictum at tempor commodo ullamcorper a lacus vestibulum sed. Pretium aenean pharetra magna ac placerat vestibulum lectus mauris ultrices. Nisl nisi scelerisque eu ultrices vitae. Vitae ultricies leo integer malesuada nunc. Etiam non quam lacus suspendisse faucibus interdum posuere.\n" +
            "\n" +
            "Convallis a cras semper auctor. Nibh mauris cursus mattis molestie a iaculis at erat. Suspendisse in est ante in nibh mauris cursus. Vitae et leo duis ut. Non odio euismod lacinia at quis. Quam elementum pulvinar etiam non quam lacus. Massa ultricies mi quis hendrerit dolor magna. Molestie a iaculis at erat pellentesque. Netus et malesuada fames ac. Quam lacus suspendisse faucibus interdum posuere lorem ipsum. Ornare aenean euismod elementum nisi quis eleifend quam adipiscing. Tellus id interdum velit laoreet id donec ultrices tincidunt. Ut tortor pretium viverra suspendisse potenti. Semper eget duis at tellus at urna condimentum mattis pellentesque.\n" +
            "\n" +
            "Urna nunc id cursus metus aliquam eleifend mi. Eleifend mi in nulla posuere sollicitudin aliquam ultrices. Neque sodales ut etiam sit. Lacus laoreet non curabitur gravida arcu ac tortor. Senectus et netus et malesuada fames. Dolor morbi non arcu risus quis. Viverra mauris in aliquam sem fringilla ut morbi. Vestibulum lectus mauris ultrices eros. Nunc pulvinar sapien et ligula. Imperdiet sed euismod nisi porta lorem mollis aliquam ut. Elementum nibh tellus molestie nunc non. Vulputate sapien nec sagittis aliquam malesuada. Nisl condimentum id venenatis a. Cursus in hac habitasse platea dictumst quisque sagittis purus sit. Sem integer vitae justo eget. Suspendisse interdum consectetur libero id faucibus nisl. Nisl tincidunt eget nullam non.\n" +
            "\n" +
            "Enim praesent elementum facilisis leo vel fringilla est. Consequat ac felis donec et odio pellentesque diam volutpat commodo. Magna ac placerat vestibulum lectus mauris ultrices eros in cursus. Tellus cras adipiscing enim eu turpis egestas pretium aenean pharetra. Est sit amet facilisis magna etiam tempor orci. In pellentesque massa placerat duis ultricies lacus sed turpis tincidunt. Cras sed felis eget velit aliquet sagittis id consectetur. Varius duis at consectetur lorem donec massa sapien. Velit egestas dui id ornare arcu odio. Morbi tincidunt augue interdum velit euismod. Sit amet est placerat in egestas erat. Mattis ullamcorper velit sed ullamcorper. Tincidunt tortor aliquam nulla facilisi cras fermentum odio. Morbi leo urna molestie at. Scelerisque in dictum non consectetur a erat nam at lectus. Viverra suspendisse potenti nullam ac tortor vitae purus faucibus. Non nisi est sit amet. Lacus luctus accumsan tortor posuere ac ut. Purus sit amet luctus venenatis.\n" +
            "\n" +
            "Ut tristique et egestas quis ipsum suspendisse ultrices gravida. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Malesuada proin libero nunc consequat interdum varius. Eu facilisis sed odio morbi quis commodo. Sit amet facilisis magna etiam tempor orci eu lobortis elementum. Iaculis at erat pellentesque adipiscing commodo elit. Vitae tortor condimentum lacinia quis vel eros. Lorem ipsum dolor sit amet consectetur adipiscing elit ut. Eget sit amet tellus cras adipiscing enim eu turpis. Tortor at auctor urna nunc id cursus. Pharetra diam sit amet nisl suscipit adipiscing bibendum est. Ut lectus arcu bibendum at varius vel pharetra. Et netus et malesuada fames ac. Augue mauris augue neque gravida in fermentum.\n" +
            "\n" +
            "Elit ut aliquam purus sit. Mi sit amet mauris commodo quis. Amet nisl purus in mollis nunc sed id semper. Tellus mauris a diam maecenas sed. Gravida neque convallis a cras semper auctor. Viverra suspendisse potenti nullam ac tortor. Eu lobortis elementum nibh tellus. Semper risus in hendrerit gravida rutrum quisque non. Cursus euismod quis viverra nibh cras pulvinar mattis nunc sed. Placerat in egestas erat imperdiet sed euismod nisi. Orci porta non pulvinar neque laoreet suspendisse interdum consectetur. Eget magna fermentum iaculis eu. Porta non pulvinar neque laoreet suspendisse interdum consectetur libero. Enim praesent elementum facilisis leo vel. Quis hendrerit dolor magna eget est lorem. Lectus sit amet est placerat. Mauris sit amet massa vitae tortor condimentum lacinia quis.\n" +
            "\n" +
            "Scelerisque fermentum dui faucibus in ornare quam viverra orci. Interdum consectetur libero id faucibus nisl. Pellentesque eu tincidunt tortor aliquam nulla facilisi cras fermentum. Bibendum arcu vitae elementum curabitur vitae. Ac orci phasellus egestas tellus. Ut faucibus pulvinar elementum integer enim neque. Mauris sit amet massa vitae tortor condimentum lacinia quis. Fermentum dui faucibus in ornare quam viverra orci. Orci dapibus ultrices in iaculis nunc sed augue lacus viverra. Sed felis eget velit aliquet. Dictum fusce ut placerat orci nulla pellentesque dignissim. Imperdiet proin fermentum leo vel orci porta non. A diam maecenas sed enim ut sem. Porta nibh venenatis cras sed felis eget velit. Quis auctor elit sed vulputate mi sit. Facilisi nullam vehicula ipsum a arcu cursus vitae congue. Sed viverra ipsum nunc aliquet bibendum enim facilisis gravida. Ac tincidunt vitae semper quis lectus nulla.";

    @Test
    public void should_return_same_text() {
        // when
        Words words = new Words(TEXT);

        // then
        assertThat(words.backToText(words.getItems())).isEqualTo(TEXT);
    }
}